# # Service Configuration
server:
   applicationConnectors:
     - type: http
       port: 9351   
       acceptorThreads: 2
       selectorThreads: 4
   #health check and admin port
   adminConnectors:
     - type: http
       port: 9350

logging:
  level: DEBUG
  appenders:
    # Log warnings and errors to file
    - type: file
      currentLogFilename: ./logs/swim-broker.log
      threshold: WARN
      queueSize: 512
      discardingThreshold: 0
      archive: true
      archivedLogFilenamePattern: ./logs/swim-broker-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m%n%rEx"
      bufferSize: 8KiB
      immediateFlush: true   
    # log debug on console (testing only)
    - type: console
      threshold: ERROR
      target: stdout

# SWIM Model Database
swimdbuser: ${SWIMDBUSER:- user}
swimdbpassword: ${SWIMDBPASSWORD:- password}
swimdbhost: ${SWIMDBHOST:- localhost}
swimdbname: ${SWIMDBNAME:- modeldb}
swimdbport:  ${SWIMDBPORT:- 27017}
swimdbauth: ${SWIMDBAUTH:- admin}  

# Workflow Database
workflowDBUser: ${WORKFLOWDBUSER:- user}
workflowDBPassword: ${WORKFLOWDBPASSWORD:- password}
workflowDBHost: ${WORKFLOWDBHOST:- localhost}
workflowDBName: ${WORKFLOWDBNAME:- workflowdb}
workflowDBPort: ${WORKFLOWDBPORT:- 27017}
workflowAuthSource: ${WORKFLOWAUTHSOURCE:- admin}

# Auth Key Database
authDBDriver: ${AUTHDBDRIVER:- mysql}
authDBHost: ${AUTHDBHOST:- localhost}
authDBPort: ${AUTHDBPORT:- 3306}
authDBName: ${AUTHDBNAME:- swim-log}
authDBUser: ${AUTHDBUSER:- swim-log}
authDBPassword: ${AUTHDBPASSWORD:- password}

# User Database
userDBDriver: ${USERDBDRIVER:- mysql}
userDBHost: ${USERDBHOST:- localhost}
userDBPort: ${USERDBPORT:- 3306}
userDBName: ${USERDBNAME:- userdb}
userDBUser: ${USERDBUSER:- userdb}
userDBPassword: ${USERDBPASSWORD:- password}

# Orchestration webservices
composerURL: ${COMPOSERURL:- http://localhost:8091/compose}
swimMergeURL: ${SWIMMERGEURL:- http://localhost:5021/swim-merge/postprocess}
serializerURL: ${SERIALIZERURL:- http://localhost:5004/workflow-cwl/workflow/serialize/}
runnerURL: ${RUNNERURL:- http://localhost:5004/workflow-cwl/workflow/execute/}

swagger:
  schemes: ['http','https']
  resourcePackage: com.utep.ilink.swim.services.controller
  title: SWIM Modeling Broker
  version: 1.0
  description: SWIM entrypoints for orchestration and execution of modeling workflows
  termsOfServiceUrl: https://swim.cybershare.utep.edu/en/policy
  licenseUrl: https://creativecommons.org/licenses/by-nc/4.0/
  contactEmail: swim@utep.edu
  enabled: true
  

